### ISSUE TITLE
packet data output in JSON format  with descriptive values

### ISSUE THREAD

**Issue by ugandhar84** [randolphcyg/gowireshark#8]
/gowireshark/tests/gowireshark_test.go:33 +0x25
testing.tRunner(0xc000110ea0, 0x57d100)
        /usr/lib/go-1.18/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
        /usr/lib/go-1.18/src/testing/testing.go:1486 +0x35f
exit status 2
FAIL    github.com/randolphcyg/gowireshark/tests        600.690s

**Comment by randolphcyg** [comment]
> /gowireshark/tests/gowireshark_test.go:33 +0x25 testing.tRunner(0xc000110ea0, 0x57d100) /usr/lib/go-1.18/src/testing/testing.go:1439 +0x102 created by testing.(*T).Run /usr/lib/go-1.18/src/testing/testing.go:1486 +0x35f exit status 2 FAIL github.com/randolphcyg/gowireshark/tests 600.690s

This should be the timeout mechanism of the go test module for 10 minutes, the reason may be that the read output data frame has been executed, and for more than 10 minutes, the go test module actively throws an error

**Comment by ugandhar84** [comment]
Okay Thank you. i m looking for one more suggestion - how to get the dissected packet in json with values in descriptive. 
     for e.g 
packet print 
F1 Application Protocol (InitialULRRCMessageTransfer)
    F1AP-PDU: initiatingMessage (0)
        initiatingMessage
            procedureCode: id-InitialULRRCMessageTransfer (11)
            
in json
[f1ap.criticality:1 f1ap.procedureCode:11 <<== i want here       "id-InitialULRRCMessageTransfer" instad number.. please advice. thank you.

**Comment by randolphcyg** [comment]
> Can you provide a sample packet file? I might be able to see if I can implement this idea~

**Comment by ugandhar84** [comment]
This is a bin file that has an f1ap setup response. i need the output to
return to the main function in JSON format layers with descriptive instead
just values in digits. Please guide me. Thank you

F1 Application Protocol (F1SetupResponse)
    F1AP-PDU: successfulOutcome (1)
        successfulOutcome
            procedureCode: id-F1Setup (1)
            criticality: reject (0)
            value
                F1SetupResponse
                    protocolIEs: 2 items
                        Item 0: id-TransactionID
                            ProtocolIE-Field
                                id: id-TransactionID (78)
                                criticality: reject (0)
                                value
                                    TransactionID: 20
                        Item 1: id-Cause
                            ProtocolIE-Field
                                id: id-Cause (0)
                                criticality: reject (0)
                                value
                                    Cause: radioNetwork (0)
                                        radioNetwork: unspecified (0)

**Comment by randolphcyg** [comment]
1.Since I couldn't find a PCAP file of F1AP protocol online, so I am unable to reproduce the real situation; Could you please send me the PCAP file so that I can verify and test it?
2.However, when testing with other existing protocol packets, you can observe that the parsing result contains descriptive values.
3.Additionally, there is a mapping of constant values for the F1AP protocol in the file ‘wireshark/epan/dissectors/asn1/f1ap/F1AP-constants.asn’. Therefore, the parsing of the F1AP protocol through the Wireshark DLL should also include descriptive values.

**Comment by randolphcyg** [comment]
> This is a bin file that has an f1ap setup response. Instead of printing output on console i need packet data output to return to the main function in JSON format layers with descriptive values. Please guide me. Thank you F1 Application Protocol (F1SetupResponse) F1AP-PDU: successfulOutcome (1) successfulOutcome procedureCode: id-F1Setup (1) criticality: reject (0) value F1SetupResponse protocolIEs: 2 items Item 0: id-TransactionID ProtocolIE-Field id: id-TransactionID (78) criticality: reject (0) value TransactionID: 20 Item 1: id-Cause ProtocolIE-Field id: id-Cause (0) criticality: reject (0) value Cause: radioNetwork (0) radioNetwork: unspecified (0)

1.Since I couldn't find a PCAP file of F1AP protocol online, so I am unable to reproduce the real situation; Could you please send me the PCAP file so that I can verify and test it?
2.However, when testing with other existing protocol packets, you can observe that the parsing result contains descriptive values.
3.Additionally, there is a mapping of constant values for the F1AP protocol in the file ‘wireshark/epan/dissectors/asn1/f1ap/F1AP-constants.asn’. Therefore, the parsing of the F1AP protocol through the Wireshark DLL should also include descriptive values.

**Comment by ugandhar84** [comment]
[f1ap.pcapng.zip](https://github.com/randolphcyg/gowireshark/files/12188837/f1ap.pcapng.zip)


please find this file which has f1apsetup

**Comment by randolphcyg** [comment]
> [f1ap.pcapng.zip](https://github.com/randolphcyg/gowireshark/files/12188837/f1ap.pcapng.zip)
> 
> please find this file which has f1apsetup

This problem has been solved, and the code is added in the tag v2.0.9;

If there is a problem, you can let me know.
